#!/usr/bin/env node
// Emits a complete, contract-conforming mascot set from a palette: one rig (eight faces,
// pivots, slots, both grip mittens) plus the four FLAT variants the app actually loads.
//
//   node build-mascot.mjs --out <dir> [--config <file.json>] [--body '#f0a828'] [--skin outline]
//   node build-mascot.mjs --print-config          # the full config with every default filled in
//
// Why this exists instead of four hand-drawn starter files: the hand-drawn ones drifted out
// of the contract and nobody noticed, because nothing renders a starter template. Generating
// from the same face source as the shipped characters is the only way they stay in step.
//
// Decorate AFTER generating: drop a hat into #slot-hat, eyewear into #slot-eyewear, a held
// item into #slot-item, add a #rig-tail. Never reshape the body capsule or move the limbs.
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { faceSet, faceGroups } from './mascot-faces.mjs';

const BODY = 'M9 4 L15 4 A4 4 0 0 1 19 8 L19 12 A4 4 0 0 1 15 16 L9 16 A4 4 0 0 1 5 12 L5 8 A4 4 0 0 1 9 4 Z';
const ARM_L = 'M1.8 9 L3.2 9 A0.8 0.8 0 0 1 4 9.8 L4 12.2 A0.8 0.8 0 0 1 3.2 13 L1.8 13 A0.8 0.8 0 0 1 1 12.2 L1 9.8 A0.8 0.8 0 0 1 1.8 9 Z';
const ARM_R = 'M20.8 9 L22.2 9 A0.8 0.8 0 0 1 23 9.8 L23 12.2 A0.8 0.8 0 0 1 22.2 13 L20.8 13 A0.8 0.8 0 0 1 20 12.2 L20 9.8 A0.8 0.8 0 0 1 20.8 9 Z';
// Fixed by the app's edge-peek overlay — recolour only, never re-place.
const MITT = (x) => `<rect x="${x}" y="8.3" width="2.6" height="3.4" rx="1.17"`;

export const DEFAULTS = {
  id: 'm',                       // prefix for gradient ids, so two rigs can share a document
  skin: 'solid',                 // 'solid' (tinted body) | 'outline' (light body + line)
  body: '#f0a828',
  highlight: '#ffd268',          // solid skin only
  shade: '#b8760f',
  line: '#2a1004',               // outline skin only — the body stroke
  face: { ink: '#2a1004' },      // + optional fill / rim / rimW for dark-bodied themes
  catchlight: 'cluster',         // 'cluster' (three sparkle dots) | 'pair' (one big shine + one small)
  spark: ['#ffc030', '#ffe090', '#ffd060'],
  accent: '#ffc030',             // the two stars on `dizzy`
  tail: false,
};

const merge = (a, b) => ({ ...a, ...b, face: { ...a.face, ...(b.face ?? {}) } });

function faceCfg(c) {
  return { ...c.face, spark: c.spark, accent: c.accent, accent2: c.accent2,
           catchlight: c.catchlight, sparkOpacity: c.sparkOpacity, extra: undefined };
}

function defs(c) {
  if (c.skin === 'outline') {
    return `  <defs>
    <linearGradient id="${c.id}-lo" x1="0" y1="0" x2="0.22" y2="1">
      <stop offset="52%" stop-color="${c.shade}" stop-opacity="0"/>
      <stop offset="100%" stop-color="${c.shade}" stop-opacity="0.55"/>
    </linearGradient>
  </defs>`;
  }
  return `  <defs>
    <radialGradient id="${c.id}-hi" cx="33%" cy="20%" r="80%">
      <stop offset="0%" stop-color="${c.highlight}" stop-opacity="0.85"/>
      <stop offset="55%" stop-color="${c.highlight}" stop-opacity="0"/>
    </radialGradient>
    <linearGradient id="${c.id}-lo" x1="0" y1="0" x2="0.22" y2="1">
      <stop offset="52%" stop-color="${c.shade}" stop-opacity="0"/>
      <stop offset="100%" stop-color="${c.shade}" stop-opacity="0.75"/>
    </linearGradient>
    <linearGradient id="${c.id}-limb" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="${c.body}"/>
      <stop offset="100%" stop-color="${c.shade}"/>
    </linearGradient>
    <radialGradient id="${c.id}-spec" cx="30%" cy="16%" r="26%">
      <stop offset="0%" stop-color="#ffffff" stop-opacity="0.5"/>
      <stop offset="100%" stop-color="#ffffff" stop-opacity="0"/>
    </radialGradient>
  </defs>`;
}

const limbPaint = (c) => c.skin === 'outline'
  ? ` fill="${c.body}" stroke="${c.line}" stroke-width="0.6"`
  : ` fill="url(#${c.id}-limb)"`;

function bodyArt(c) {
  if (c.skin === 'outline') {
    return `      <path d="${BODY}" fill="${c.body}" stroke="${c.line}" stroke-width="0.6"/>
      <path d="${BODY}" fill="url(#${c.id}-lo)"/>`;
  }
  // Highlights are invisible on a light body — that is why `outline` drops them and carries
  // the depth in the shade gradient alone.
  return `      <path d="${BODY}" fill="${c.body}"/>
      <path d="${BODY}" fill="url(#${c.id}-lo)"/>
      <path d="${BODY}" fill="url(#${c.id}-hi)"/>
      <ellipse cx="9.6" cy="6.4" rx="3.4" ry="1.9" fill="url(#${c.id}-spec)" transform="rotate(-14 9.6 6.4)"/>`;
}

export function buildRig(cfg) {
  const c = merge(DEFAULTS, cfg);
  const p = limbPaint(c);
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="-3 -5 30 30">
  <!-- Generated by build-mascot.mjs. Decorate the slots; do not reshape the body or move
       the limbs. Contract: wecoded-themes mascots/README.md -->
${defs(c)}
  <g id="rig-root">${c.tail ? `
    <g id="rig-tail" data-pivot="19 14"><path d="M19 14 Q21 14 21.5 15.5 Q22 17 20.5 17.2 L21 18.6 L19.5 18.2 Z"${p}/></g>` : ''}
    <g id="rig-arm-left" data-pivot="2.5 9"><path d="${ARM_L}"${p}/></g>
    <g id="rig-arm-right" data-pivot="21.5 9"><path d="${ARM_R}"${p}/>
      <g id="slot-item"/>
    </g>
    <g id="rig-leg-left" data-pivot="8.95 17"><rect x="7.2" y="17" width="3.5" height="4" rx="1.2"${p}/></g>
    <g id="rig-leg-right" data-pivot="15.05 17"><rect x="13.3" y="17" width="3.5" height="4" rx="1.2"${p}/></g>
    <g id="rig-body">
${bodyArt(c)}
${faceGroups(faceCfg(c))}
      <g id="slot-eyewear"/>
    </g>
    <g id="slot-hat"/>
    <g id="rig-hand-peek-right" style="display:none">${MITT('20.7')}${p}/></g>
    <g id="rig-hand-peek-left" style="display:none">${MITT('0.7')}${p}/></g>
  </g>
</svg>
`;
}

// The app loads flat variants through <img>, where currentColor renders BLACK and CSS
// variables never resolve (measured 2026-09-05). Flat art is hardcoded hex, always.
const FLAT = { idle: 'idle', welcome: 'welcome', inquisitive: 'curious', shocked: 'shocked' };

export function buildFlat(cfg, variant) {
  // Refuse rather than emit a broken file. `dizzy` is a rig FACE with no flat counterpart;
  // asking for one silently produced an empty SVG, which is how two shipped themes ended up
  // carrying a mascot-dizzy.svg the app resolves and can never display.
  if (!(variant in FLAT)) {
    throw new Error(`no flat variant "${variant}" — the app displays only ${Object.keys(FLAT).join(', ')}`);
  }
  const c = merge(DEFAULTS, cfg);
  const F = faceSet(faceCfg(c));
  const p = limbPaint(c);
  const extra = (c.extra ?? (() => ''))(FLAT[variant]);
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="-3 -5 30 30">
  <!-- Generated by build-mascot.mjs — flat "${variant}" variant (rig face "${FLAT[variant]}").
       Hardcoded colours on purpose: this renders through <img>, where currentColor is black. -->
${defs(c)}${c.tail ? `
  <path d="M19 14 Q21 14 21.5 15.5 Q22 17 20.5 17.2 L21 18.6 L19.5 18.2 Z"${p}/>` : ''}
  <path d="${ARM_L}"${p}/>
  <path d="${ARM_R}"${p}/>
  <rect x="7.2" y="17" width="3.5" height="4" rx="1.2"${p}/>
  <rect x="13.3" y="17" width="3.5" height="4" rx="1.2"${p}/>
${bodyArt(c)}
  ${F[FLAT[variant]]}${extra}
</svg>
`;
}

function main(argv) {
  const arg = (k, d) => { const i = argv.indexOf(k); return i < 0 ? d : argv[i + 1]; };
  if (argv.includes('--print-config')) { console.log(JSON.stringify(DEFAULTS, null, 2)); return 0; }
  const out = arg('--out');
  if (!out) { console.error('usage: build-mascot.mjs --out <dir> [--config <file.json>] [--body <hex>] [--skin solid|outline]'); return 1; }
  let cfg = {};
  const cf = arg('--config');
  if (cf) cfg = JSON.parse(readFileSync(cf, 'utf8'));
  if (arg('--body')) cfg.body = arg('--body');
  if (arg('--skin')) cfg.skin = arg('--skin');
  mkdirSync(out, { recursive: true });
  writeFileSync(join(out, 'mascot-rig.svg'), buildRig(cfg));
  for (const v of Object.keys(FLAT)) writeFileSync(join(out, `mascot-${v}.svg`), buildFlat(cfg, v));
  console.log(`wrote mascot-rig.svg + ${Object.keys(FLAT).length} flat variants to ${out}`);
  return 0;
}

if (import.meta.url === `file://${process.argv[1]}`) process.exit(main(process.argv.slice(2)));
